/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5b46308c-1f86-465c-91d9-8a5bbf548eef",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_O58y2qC0p",
    "aws_user_pools_web_client_id": "5d0aoih5a3g5hehqoh42bqjeo4",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://bu4xlmwbhzaa3njuggmghghdzy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-nm6uziwaujcb7bhgnjbvwgqlj4",
    "aws_user_files_s3_bucket": "amplifyreactgraphqlforimagestorage144654-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
